openapi: 3.0.3
info:
  title: Add yout API title HERE.
  description: Your API description HERE.
  version: 0.4.0
tags:
  - name: seller
    description: Service description HERE.
  - name: inventory
    description: Service description HERE.
  - name: buyer
    description: Service description HERE.
paths:
  /seller:
    post:
      tags:
        - seller
      summary: Add a summary HERE.
      description: Add a description HERE.
      operationId: createSeller
      requestBody:
        description: Add a payload description HERE.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SellerCreationRequest"
        required: true
      responses:
        400:
          description: Add description HERE.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SellerPOSTErrorResponse"
  /seller/{sellerId}:
    get:
      tags:
        - seller
      summary: Add a summary HERE.
      description: Add a description HERE.
      operationId: getSeller
      parameters:
        - name: sellerId
          in: path
          description: Add description HERE.
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Add description HERE.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SellerResponse"
        404:
          description: Add description HERE.
          content: {}
components:
  schemas:
    SellerCreationRequest:
      required:
        - name
        - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: doggie
        photoUrls:
          type: array
          items:
            type: string
        status:
          type: string
          description: pet status in the store
          enum:
            - available
            - pending
            - sold
    SellerResponse:
      required:
        - name
        - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: doggie
        photoUrls:
          type: array
          items:
            type: string
        status:
          type: string
          description: pet status in the store
          enum:
            - available
            - pending
            - sold
    SellerPOSTErrorResponse:
      type: object
      properties:
        code:
          type: string
          enum:
            - MISSING_FIELD
            - INVALID_DATE
        message:
          type: string
